import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  applySectionToFile,
  parseTemplate,
  readSectionFromFile,
  renderTemplateSection
} from './index.js';

const TEMPLATE_YAML = `
id: prd
version: 1
title: Product Requirements Document
owner: athena
inputs:
  - name: problem_statement
    type: text
    required: true
  - name: users
    type: list
sections:
  - id: problem
    title: Problem
    elicit: true
    body: |
      {{problem_statement}}
  - id: users
    title: Users
    repeatable: true
    body: |
      - {{item}}
  - id: out-of-scope
    title: Out of scope
    body: |
      Nothing yet.
`;

describe('renderTemplateSection', () => {
  const template = (() => {
    const r = parseTemplate(TEMPLATE_YAML, '/virtual/prd.yaml');
    if (!r.ok) throw new Error(r.error.message);
    return r.value;
  })();

  it('renders a single named top-level section without preamble or title header', () => {
    const r = renderTemplateSection({
      template,
      sectionId: 'problem',
      inputs: { problem_statement: 'Users lose context across sessions.' },
      callingAgent: { name: 'athena' }
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.sectionId).toBe('problem');
    // No `# Product Requirements Document` and no generator comment.
    expect(r.value.content).not.toContain('# Product Requirements Document');
    expect(r.value.content).not.toContain('generated by atlas');
    expect(r.value.content).toContain('## Problem');
    expect(r.value.content).toContain('Users lose context across sessions.');
  });

  it('reports TEMPLATE_SECTION_NOT_FOUND for an unknown id', () => {
    const r = renderTemplateSection({
      template,
      sectionId: 'nonexistent',
      inputs: { problem_statement: 'x' },
      callingAgent: { name: 'athena' }
    });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.error.code).toBe('TEMPLATE_SECTION_NOT_FOUND');
  });

  it('honors the elicit gate on a single section', () => {
    const r = renderTemplateSection({
      template,
      sectionId: 'problem',
      inputs: {}, // missing problem_statement
      callingAgent: { name: 'athena' }
    });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.error.code).toBe('TEMPLATE_INPUT_MISSING');
  });

  it('honors owner enforcement when calling agent is not authorized', () => {
    const r = renderTemplateSection({
      template,
      sectionId: 'out-of-scope',
      inputs: { problem_statement: 'x' },
      callingAgent: { name: 'hercules' }
    });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.error.code).toBe('TEMPLATE_OWNER_MISMATCH');
  });

  it('renders a repeatable section in isolation', () => {
    const r = renderTemplateSection({
      template,
      sectionId: 'users',
      inputs: { problem_statement: 'x', users: ['Alice', 'Bob'] },
      callingAgent: { name: 'athena' }
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.content).toContain('- Alice');
    expect(r.value.content).toContain('- Bob');
  });
});

describe('applySectionToFile / readSectionFromFile', () => {
  let dir: string;
  let file: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'atlas-section-'));
    file = join(dir, 'sub', 'prd.md');
  });
  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('creates the file with preamble + a single section block on first call', async () => {
    const r = await applySectionToFile({
      filePath: file,
      sectionId: 'problem',
      content: '## Problem\n\nUsers lose context.\n',
      preamble: '# PRD'
    });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.created).toBe(true);
    expect(r.value.fileCreated).toBe(true);
    const out = await readFile(file, 'utf8');
    expect(out.startsWith('# PRD\n\n<!-- atlas:section problem -->\n')).toBe(true);
    expect(out).toContain('<!-- /atlas:section problem -->');
  });

  it('appends a new section to an existing file', async () => {
    await applySectionToFile({ filePath: file, sectionId: 'problem', content: 'A\n', preamble: '# PRD' });
    const r = await applySectionToFile({ filePath: file, sectionId: 'users', content: 'B\n' });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.created).toBe(true);
    expect(r.value.fileCreated).toBe(false);
    const out = await readFile(file, 'utf8');
    expect(out.indexOf('atlas:section problem')).toBeLessThan(
      out.indexOf('atlas:section users')
    );
    // Both blocks present.
    expect((out.match(/<!-- atlas:section /g) ?? []).length).toBe(2);
  });

  it('replaces an existing section in place (idempotent)', async () => {
    await applySectionToFile({ filePath: file, sectionId: 'problem', content: 'first\n' });
    const r = await applySectionToFile({ filePath: file, sectionId: 'problem', content: 'second\n' });
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value.created).toBe(false);
    const out = await readFile(file, 'utf8');
    expect(out).toContain('second');
    expect(out).not.toContain('first');
    // Still exactly one block.
    expect((out.match(/<!-- atlas:section problem -->/g) ?? []).length).toBe(1);
  });

  it('preserves order and unrelated content when replacing the middle section', async () => {
    await applySectionToFile({ filePath: file, sectionId: 'a', content: 'AAA' });
    await applySectionToFile({ filePath: file, sectionId: 'b', content: 'BBB' });
    await applySectionToFile({ filePath: file, sectionId: 'c', content: 'CCC' });
    await applySectionToFile({ filePath: file, sectionId: 'b', content: 'BBB-2' });
    const out = await readFile(file, 'utf8');
    const ai = out.indexOf('AAA');
    const bi = out.indexOf('BBB-2');
    const ci = out.indexOf('CCC');
    expect(ai).toBeGreaterThanOrEqual(0);
    expect(bi).toBeGreaterThan(ai);
    expect(ci).toBeGreaterThan(bi);
    expect(out).not.toContain('BBB\n'); // old body gone
  });

  it('rejects malformed section ids', async () => {
    const r = await applySectionToFile({ filePath: file, sectionId: 'NotKebab', content: 'x' });
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.error.code).toBe('TEMPLATE_SECTION_WRITE_FAILED');
  });

  it('readSectionFromFile returns the body without markers', async () => {
    await applySectionToFile({ filePath: file, sectionId: 'problem', content: 'hello world' });
    const r = await readSectionFromFile(file, 'problem');
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    expect(r.value).toBe('hello world');
  });

  it('readSectionFromFile returns undefined when file or section missing', async () => {
    const noFile = await readSectionFromFile(join(dir, 'nope.md'), 'problem');
    expect(noFile.ok).toBe(true);
    if (noFile.ok) expect(noFile.value).toBeUndefined();

    const stub = join(dir, 'stub.md');
    await writeFile(stub, '# stub\n');
    const noSection = await readSectionFromFile(stub, 'problem');
    expect(noSection.ok).toBe(true);
    if (noSection.ok) expect(noSection.value).toBeUndefined();
  });
});
