/**
 * Skill = procedural knowledge bundle that an agent can load on-demand.
 *
 * Format: `~/.atlas/skills/<name>/SKILL.md` with YAML frontmatter:
 *
 *   ---
 *   name: my-skill
 *   description: One-line description shown in the skill index.
 *   triggers:
 *     - "react component"
 *     - "tailwind"
 *   ---
 *   # body markdown describing the procedure...
 */
import { z } from 'zod';

export const SkillFrontmatterSchema = z.object({
  name: z.string().min(1),
  description: z.string().min(1),
  /** Optional substring/regex triggers the agent matches against context. */
  triggers: z.array(z.string()).default([]),
  /**
   * Origin of the skill. Drives scope rules in `buildSystemPrompt`:
   *  - `builtin`  — shipped with Atlas (always available, all agents).
   *  - `user`     — hand-authored by the user (always available, all agents).
   *  - `learned`  — auto-generated by the self-improvement loop. Scoped to
   *                 framework agents only; not exposed to user agents and
   *                 not invokable via any future `/skillname` shortcut.
   */
  kind: z.enum(['builtin', 'user', 'learned']).default('user'),
  /** Agent that created this skill (only meaningful for `kind: learned`). */
  createdBy: z.string().optional(),
  /** Session id this skill was distilled from. */
  createdFromSession: z.string().optional(),
  /** One-line "why was this created" shown to the user when reviewing. */
  createdReason: z.string().optional(),
  /**
   * Semantic version of the skill body. Hand-authored skills default to
   * `0.1.0`; learned skills get bumped automatically when re-distilled.
   * Used by the `/skills history` UI and future skill-merging logic.
   */
  version: z.string().default('0.1.0'),
  /** ISO-8601 UTC timestamp of creation. Auto-set by `saveLearnedSkill`. */
  createdAt: z.string().optional(),
  /**
   * When `true`, the loader keeps the file on disk but excludes the
   * skill from every registry (and therefore every system prompt).
   * Toggled via `/skills disable <name>` / `/skills enable <name>`.
   * Lets users mute a noisy learned skill without losing it.
   */
  disabled: z.boolean().optional()
});

export type SkillFrontmatter = z.infer<typeof SkillFrontmatterSchema>;

export interface Skill extends SkillFrontmatter {
  /** Absolute path to SKILL.md. */
  readonly path: string;
  /** The markdown body (everything after the frontmatter). */
  readonly body: string;
}
